// Mirrors the Pydantic models in src/home_weather_hub/dashboard_api.py.
// In Phase 2 these will be generated by openapi-typescript.

export type MetricKey =
  | 'outdoor.air_temp_c'
  | 'outdoor.air_temp_f'
  | 'outdoor.relative_humidity_pct'
  | 'outdoor.pressure_mb'
  | 'outdoor.wind_avg_mph'
  | 'outdoor.wind_gust_mph'
  | 'outdoor.wind_direction_deg'
  | 'outdoor.uv_index'
  | 'outdoor.illuminance_lux'
  | 'outdoor.solar_radiation_w_m2'
  | 'outdoor.rain_accumulated_in'
  | 'outdoor.battery_voltage'
  | 'outdoor.rapid_wind_speed_mph'
  | 'outdoor.rapid_wind_direction_deg';

export interface ObsSt {
  type: 'obs_st';
  time_epoch: number | null;
  air_temp_c: number | null;
  air_temp_f: number | null;
  relative_humidity_pct: number | null;
  pressure_mb: number | null;
  wind_avg_mps: number | null;
  wind_avg_mph: number | null;
  wind_gust_mps: number | null;
  wind_gust_mph: number | null;
  wind_direction_deg: number | null;
  uv_index: number | null;
  illuminance_lux: number | null;
  rain_accumulated_mm: number | null;
  rain_accumulated_in: number | null;
  battery_voltage: number | null;
  received_at?: string;
}

export interface RapidWind {
  type: 'rapid_wind';
  time_epoch: number | null;
  wind_speed_mps: number | null;
  wind_speed_mph: number | null;
  wind_direction_deg: number | null;
}

export interface EvtStrike {
  type: 'evt_strike';
  time_epoch: number | null;
  distance_km: number | null;
  distance_mi: number | null;
  energy: number | null;
}

export type DecodedEvent = ObsSt | RapidWind | EvtStrike;

export interface SnapshotResponse {
  events: { obs_st?: ObsSt; rapid_wind?: RapidWind; evt_strike?: EvtStrike };
  metrics: Partial<Record<MetricKey, number | null>>;
}

export interface HistoryPoint { t: number; v: number }
export interface HistoryResponse { metric: MetricKey; points: HistoryPoint[] }

export interface Strike { t: number; distance_km: number; energy: number }
export interface StrikesResponse { strikes: Strike[] }

export interface StationConfig {
  lat: number | null;
  lng: number | null;
  name: string | null;
  metric_keys: MetricKey[];
}

export interface WidgetConfig {
  i: string;
  metric: MetricKey;
  display: 'big-number' | 'graph';
  stat: 'current' | 'min' | 'max' | 'mean';
  kind?: 'metric' | 'wind' | 'strikes';
}

export interface LayoutItem {
  i: string;
  x: number;
  y: number;
  w: number;
  h: number;
  minW?: number;
  minH?: number;
}

export type Breakpoint = 'tv' | 'mac' | 'tablet' | 'phone';

export interface SavedLayouts {
  widgets: WidgetConfig[];
  layouts: Record<Breakpoint, LayoutItem[]>;
}
